#!/usr/bin/env node
/**
 * Generate .github/dependabot.yml from templates.json.
 *
 *   node scripts/dependabot-config.mjs            # write the file
 *   node scripts/dependabot-config.mjs --check    # exit 1 if it is stale
 *
 * One `updates` entry per framework family, each with its own directory list
 * and its own grouped security update. Dependabot opens at most one PR per
 * group, so a single catch-all group across all templates meant one
 * unmergeable PR (for example a Nuxt template waiting on an upstream fix)
 * blocked every later advisory in every other template. Per-family groups
 * keep that blast radius to the family.
 *
 * Every template with a package.json must land in exactly one family. Run
 * this after adding a template; CI fails if the committed file is stale.
 */
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const catalogPath = join(root, 'templates.json');
const outputPath = join(root, '.github', 'dependabot.yml');
const check = process.argv.includes('--check');

// Family name -> primary framework names as written in templates.json
// (`technology.frameworks[0]`). Keep names lower-case; matching is
// case-insensitive.
const FAMILIES = {
  next: ['next.js'],
  nuxt: ['nuxt'],
  astro: ['astro'],
  svelte: ['svelte', 'sveltekit'],
  vue: ['vue'],
  react: ['react'],
  'node-servers': ['nestjs', 'hono', 'fastify', 'express'],
  other: [],
};

const { templates } = JSON.parse(readFileSync(catalogPath, 'utf8'));
const members = Object.fromEntries(Object.keys(FAMILIES).map((name) => [name, []]));
const problems = [];

for (const template of templates) {
  if (!existsSync(join(root, 'templates', template.id, 'package.json'))) {
    continue;
  }

  const framework = String(template.technology?.frameworks?.[0] ?? '').toLowerCase();
  const family =
    Object.entries(FAMILIES).find(([, names]) => names.includes(framework))?.[0] ?? 'other';
  members[family].push(template.id);
}

for (const [family, ids] of Object.entries(members)) {
  if (ids.length === 0 && family !== 'other') {
    problems.push(`family "${family}" has no templates`);
  }
}

// A template directory that is not in the catalog would get no Dependabot
// coverage at all, silently.
const catalogued = new Set(templates.map((template) => template.id));
for (const id of readdirSync(join(root, 'templates'))) {
  if (existsSync(join(root, 'templates', id, 'package.json')) && !catalogued.has(id)) {
    problems.push(`templates/${id} has a package.json but no entry in templates.json`);
  }
}

if (problems.length > 0) {
  console.error(problems.join('\n'));
  process.exit(1);
}

const entries = Object.entries(members)
  .filter(([, ids]) => ids.length > 0)
  .map(([family, ids]) => {
    const directories = ids
      .sort()
      .map((id) => `      - "/templates/${id}"`)
      .join('\n');

    return `  # ${family}
  - package-ecosystem: npm
    directories:
${directories}
    schedule:
      interval: daily
    open-pull-requests-limit: 0
    groups:
      ${family}-security:
        applies-to: security-updates
        patterns:
          - "*"
`;
  });

const output = `# Generated by scripts/dependabot-config.mjs from templates.json. Do not edit
# by hand; run \`npm run dependabot-config\` after adding or removing a template.
#
# Version updates are off (open-pull-requests-limit: 0). Security updates
# stay on and are grouped per framework family, so one advisory opens one PR
# across every template in that family, and a PR that cannot merge (for
# example waiting on an upstream fix) only blocks its own family.
version: 2
updates:
${entries.join('\n')}`;

if (check) {
  const current = existsSync(outputPath) ? readFileSync(outputPath, 'utf8') : '';
  if (current !== output) {
    console.error(
      '.github/dependabot.yml is out of date with templates.json. Run `npm run dependabot-config` and commit the result.',
    );
    process.exit(1);
  }
  console.log('.github/dependabot.yml is up to date.');
  process.exit(0);
}

writeFileSync(outputPath, output);
for (const [family, ids] of Object.entries(members)) {
  if (ids.length > 0) {
    console.log(`${family}: ${ids.length} template${ids.length === 1 ? '' : 's'}`);
  }
}
