<template>
  <svg
    class="art-ripples"
    viewBox="0 0 560 560"
    fill="none"
    aria-hidden="true"
    focusable="false"
  >
    <!-- Three gathering circles: one per service, meeting in the middle -->
    <circle
      cx="352"
      cy="196"
      r="150"
      fill="var(--c-lavender)"
      fill-opacity="0.24"
      stroke="var(--c-lavender-deep)"
      stroke-opacity="0.4"
      stroke-width="1.5"
    />
    <circle
      cx="216"
      cy="272"
      r="168"
      fill="var(--c-dusk)"
      fill-opacity="0.12"
      stroke="var(--c-dusk)"
      stroke-opacity="0.38"
      stroke-width="1.5"
    />
    <circle
      cx="348"
      cy="376"
      r="128"
      fill="var(--c-sand)"
      fill-opacity="0.18"
      stroke="var(--c-sand)"
      stroke-opacity="0.45"
      stroke-width="1.5"
    />
    <!-- Quiet ripples spreading outward -->
    <circle
      cx="292"
      cy="284"
      r="236"
      stroke="var(--c-dusk)"
      stroke-opacity="0.16"
      stroke-width="1.2"
    />
    <circle
      cx="292"
      cy="284"
      r="262"
      stroke="var(--c-dusk)"
      stroke-opacity="0.09"
      stroke-width="1.2"
    />
    <circle
      cx="292"
      cy="284"
      r="66"
      stroke="var(--c-lavender-deep)"
      stroke-opacity="0.35"
      stroke-width="1.2"
    />
    <circle
      cx="292"
      cy="284"
      r="5"
      fill="var(--c-dusk-deep)"
    />
  </svg>
</template>
